---
# Source: keda/templates/metrics-server/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-operator-external-metrics-reader    
    helm.sh/chart: keda-2.18.3
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.18.3
    app.kubernetes.io/instance: keda
  name: keda-operator-external-metrics-reader
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - 'externalmetrics'
  verbs:
  - 'get'
