---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 8081
    protocol: TCP
    targetPort: 8081
