---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:4318
      prometheus/kgateway-dataplane:
        config:
          global:
            scrape_protocols: [ PrometheusProto, OpenMetricsText1.0.0, OpenMetricsText0.0.1, PrometheusText0.0.4 ]
          scrape_configs:
          # Scrape the kgateway proxy pods
          - job_name: kgateway-gateways
            honor_labels: true
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_kgateway]
                action: keep
                regex: kube-gateway
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_ip
                - __meta_kubernetes_pod_annotation_prometheus_io_port
                separator: ':'
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: kube_namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod
    processors:
      batch:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s
      k8sattributes:
        auth_type: 'serviceAccount'
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.replicaset.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

    exporters:
      prometheusremotewrite/kube-prometheus-stack:
        endpoint: https://thanos-receive.airpay.codes/api/v1/write

    service:
      pipelines:
        metrics/gateways:
          receivers: [prometheus/kgateway-dataplane]
          processors: [k8sattributes, batch]
          exporters: [prometheusremotewrite/kube-prometheus-stack]
        metrics/apps:
          receivers: [otlp]
          processors: [k8sattributes, batch]
          exporters: [prometheus]
