# In the Gateway API model, it is often cleaner to explicitly create a Certificate resource.
# This resource bridges the Issuer and your Gateway.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-secret-airpay
  namespace: platform-gateways
spec:
  secretName: argocd-tls-secret-airpay
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: argocd.airpay.codes
  dnsNames:
    - argocd.airpay.codes
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atlantis-tls-secret-airpay
  namespace: platform-gateways
spec:
  secretName: atlantis-tls-secret-airpay
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: atlantis.airpay.codes
  dnsNames:
    - atlantis.airpay.codes
---
