---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.32.0
        args:
        - query
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+_grpc._tcp.thanos-store-headless.monitoring.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive-headless.monitoring.svc.cluster.local
        - --query.replica-label=replica
        ports:
        - containerPort: 9090
          name: http
        - containerPort: 10901
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
spec:
  type: ClusterIP
  selector:
    app: thanos-query
  ports:
  - name: http
    port: 9090
    targetPort: 9090
