---
# Source: kgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kgateway
  namespace: platform-gateways
  labels:
    helm.sh/chart: kgateway-v2.1.2
    kgateway: kgateway
    app.kubernetes.io/name: kgateway
    app.kubernetes.io/instance: kgateway
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: kgateway/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kgateway-role-platform-gateways
subjects:
- kind: ServiceAccount
  name: kgateway
  namespace: platform-gateways
roleRef:
  kind: ClusterRole
  name: kgateway-platform-gateways
  apiGroup: rbac.authorization.k8s.io
